# Generated by Django 4.1 on 2022-09-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myprojects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('url', models.URLField(null=True)),
                ('banner', models.ImageField(upload_to='banner')),
                ('date', models.DateField()),
            ],
        ),
    ]
